### PR TITLE
[CS2113T-F14-4]-ttippinyu-B-DoWithinPeriodTasks

### PR DESCRIPTION
**Pull request by ttippinyu**
1. Added in Within task

2. Added in tests

### CODE REVIEW

**Comment by lackmoo** [comment]
@ttippinyu spotted an error in AddCommand under IndexOutOfBoundsException, for event and within, date format is not standardised. On top of that, the input format for within should be 
"between -> and" and not "between -> to".

**Comment by ttippinyu** [comment]
> @ttippinyu spotted an error in AddCommand under IndexOutOfBoundsException, for event and within, date format is not standardised. On top of that, the input format for within should be
> "between -> and" and not "between -> to".

**Comment by ttippinyu** [comment]
The test failed because creating a DateTime object is abnormal. E.g.

Date date = new Date(119, 1,1, 12, 0); 
date.toString() >> 02/01/2019 12:00

**Comment by ttippinyu** [comment]
Have resolved the issue. Just used a parser to create date from string instead!! :))

**Comment by rssujay** [comment]
Thanks, please add the appropriate tag.

**Pull request merged**
